# Base
BASE_URL = "https://mspapi.eset.com"
API_BASE = "/api"
HTTP_TIMEOUT = 60
HTTP_LIMIT = 25

# Billing Report
BILLING_REPORT_BASE = f"{API_BASE}/BillingReport"
BILLING_REPORT_DIVISION_UNDER_SELECTED_DISTRIBUTOR = (
    f"{BILLING_REPORT_BASE}/DivisionsUnderSelectedDistributor"
)
BILLING_REPORT_MY_COMPANY = f"{BILLING_REPORT_BASE}/MyCompany"
BILLING_REPORT_MY_COMPANY_SELECTED_COMPANIES_ONLY = (
    f"{BILLING_REPORT_BASE}/MyCompanySelectedCompaniesOnly"
)
BILLING_REPORT_SINGLE_MANAGED_COMPANY = f"{BILLING_REPORT_BASE}/SingleManagedCompany"

# Company
COMPANY_BASE = f"{API_BASE}/Company"
COMPANY_DESCENDANTS = f"{COMPANY_BASE}/Descendants"

# Token
TOKEN_BASE = f"{API_BASE}/Token"
TOKEN_CHECK = f"{TOKEN_BASE}/Check"
TOKEN_GET = f"{TOKEN_BASE}/Get"
TOKEN_RENEW = f"{TOKEN_BASE}/Renew"

# Usage Report
USAGE_REPORT_BASE = f"{API_BASE}/UsageReport"
USAGE_REPORT_MONTHLY_BASE = f"{USAGE_REPORT_BASE}/Monthly"
USAGE_REPORT_MONTHLY_PRODUCTS = f"{USAGE_REPORT_MONTHLY_BASE}/products"
USAGE_REPORT_SELECTED_COMPANIES_BASE = f"{USAGE_REPORT_BASE}/SelectedCompanies"
USAGE_REPORT_SELECTED_COMPANIES_PRODUCTS = f"{USAGE_REPORT_SELECTED_COMPANIES_BASE}/products"

# Version
VERSION_BASE = f"{API_BASE}/Version"
